name: Sincronizar tareas Todoist → Notion

on:
  workflow_dispatch:
  repository_dispatch:
    types: [notion_trigger]


jobs:
  run-sync:
    runs-on: ubuntu-latest

    env:  # Inyecta secretos como variables de entorno
      TODOIST_API_TOKEN: ${{ secrets.TODOIST_API_TOKEN }}
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      TODOIST_INBOX_PROJECT_ID: ${{ secrets.TODOIST_INBOX_PROJECT_ID }}
      GITHUB_ACTIONS: "true"  # Para evitar que cargue .env en Actions

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: pip install requests python-dotenv

      - name: Ejecutar sincronización
        run: python tasks.py
